# fly.toml app configuration file generated for co-pilotsql on 2024-12-25T19:28:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'co-pilotsql'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
